branches:
  only:
    - master

# the VS C++ compiler path, doesn't seem to exist in the PATH environment variable of
# the Visual Studio 2017 build VM, due to which the pyosreplace package fails to build
image: Visual Studio 2015

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\build.cmd"
    EMULATOR_LOC: C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\Storage Emulator\\AzureStorageEmulator.exe
    ZARR_TEST_ABS: 1

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%CMD_IN_ENV% python -m pip install -U pip setuptools wheel"
  - "%CMD_IN_ENV% python -m pip install -r requirements_dev_numpy.txt -r requirements_dev_minimal.txt -r requirements_dev_optional.txt"
  - "%CMD_IN_ENV% python setup.py install"
  - "%CMD_IN_ENV% python -m pip freeze"

build: off

before_test:
  - '"%EMULATOR_LOC%" start'
  - '"%EMULATOR_LOC%" status'

test_script:
  - "%CMD_IN_ENV% python -m pytest -v --pyargs zarr"

after_test:
  - '"%EMULATOR_LOC%" stop'
