branches:
  only:
    - master

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\build.cmd"

  matrix:

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      DISTUTILS_USE_SDK: "1"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"

install:
  - cmd: |
    "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" start
    "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" status
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "%CMD_IN_ENV% python -m pip install -U pip setuptools wheel"
  - "%CMD_IN_ENV% python -m pip install -rrequirements_test.txt"
  - "%CMD_IN_ENV% python -m pip install -rrequirements_dev_npy.txt"
  - "%CMD_IN_ENV% python -m pip install --no-binary=numcodecs -rrequirements_dev.txt"
  - "%CMD_IN_ENV% python setup.py install"
  - "%CMD_IN_ENV% python -m pip freeze"

build: off

test_script:
  - "%CMD_IN_ENV% python -m pytest -v --pyargs zarr"

on_finish:
  - cmd: |
    "C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe" stop
