branches:
  only:
    - master

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\build.cmd"

  matrix:

    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      DISTUTILS_USE_SDK: "1"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4"
      DISTUTILS_USE_SDK: "1"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

build: off

test_script:
  - "%CMD_IN_ENV% python -m pip install -U pip setuptools wheel"
  - "%CMD_IN_ENV% python -m pip install -rrequirements_dev.txt"
  - "%CMD_IN_ENV% python setup.py bdist_wheel"
  - "%CMD_IN_ENV% python -m pytest -v zarr"
