channels:
  - conda-forge
  - defaults
dependencies:
  - wheel
  - numcodecs >= 0.6.4
  - numpy >= 1.21
  - pip
  - pip:
    - asciitree
    - fasteners
    - pytest
    - pytest-timeout
    - setuptools_scm
