name: Check changelog entries

on:
  pull_request:

jobs:
  check-changelogs:
    name: Check changelog entries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #Â v6.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0

      - name: Check changelog entries
        run: uv run --no-sync python ci/check_changelog_entries.py
