name: Check changelog entries

on:
  pull_request:

jobs:
  check-changelogs:
    name: Check changelog entries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 #Â v6.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6

      - name: Check changelog entries
        run: uv run --no-sync python ci/check_changelog_entries.py
